org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21.0.10

# Fabric Properties (https://fabricmc.net/develop)

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.3

# Mod Properties
mod_version=18.2-1.21.8
maven_group=com.example
archives_base_name=xiaohe66-meteor-lotus

# Dependencies

fabric_api_version=0.134.0+1.21.8

# Meteor (https://maven.meteordev.org)
meteor_version=1.21.8-SNAPSHOT

# Baritone (https://maven.meteordev.org)
baritone_version=1.21.8-SNAPSHOT

malilib_version = 1.21.8-0.25.5-sakura.2

litematica_version = 1.21.8-0.23.5